name: tanager-pigment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - rasterio
  - spectral
  - jupyter
  - pip
  - pip:
      - prosail
